### ISSUE TITLE
DaemonSet Labels Invalid Value

### ISSUE THREAD

**Issue by nyulawbrian** [draios/sysdig-cloud-scripts#133]
kubectl returns the following error when trying to apply **sysdig-agent-daemonset-v2.yaml**.

> The DaemonSet "sysdig-agent" is invalid: 
> spec.template.metadata.labels: Invalid value: map[string]string{"app":"sysdig-agent"}: `selector` does not match template `labels`
> spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"sysdig-agent", "name":"sysdig-agent"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

According to [Kubernetes documentation](https://v1-15.docs.kubernetes.io/docs/concepts/workloads/controllers/daemonset/#create-a-daemonset) the Selector and Template labels should be `name`, as per below, but the file as provided uses `app`.

```yaml
spec:
  selector:
    matchLabels:
      name: sysdig-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: sysdig-agent
```

I experienced this on a fairly vanilla installation of Kubernetes v1.14.
